version: 2

sources:
  - name: website
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    loaded_at_field: effective_from_ts
    tables:
      - name: content
      - name: sub_activate
      - name: sub_deactivate
      - name: web_events
        # freshness: # make this a little more strict
        #   warn_after: {count: 6, period: hour}
        #   error_after: {count: 12, period: hour}
  - name: workday
    # freshness: # default freshness
    #   warn_after: {count: 12, period: hour}
    #   error_after: {count: 24, period: hour}
    # loaded_at_field: _airbyte_emitted_at
    tables:
      - name: data_employees
        # freshness: # make this a little more strict
        #   warn_after: {count: 6, period: hour}
        #   error_after: {count: 12, period: hour}
