USE ROLE ACCOUNTADMIN; -- you need accountadmin (or security admin) for user creation, future grants


DROP USER IF EXISTS DBT_TEMPLATE_PROJECT_DBT_CLOUD;
DROP ROLE IF EXISTS DBT_TEMPLATE_PROJECT_TRANSFORMER;
DROP DATABASE IF EXISTS DBT_TEMPLATE_PROJECT_DATABASE CASCADE;
DROP WAREHOUSE IF EXISTS DBT_TEMPLATE_PROJECT_TRANSFORMING;

-- creating a warehouse
CREATE WAREHOUSE DBT_TEMPLATE_PROJECT_TRANSFORMING WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE COMMENT = 'Warehouse to transform data';

-- creating database
CREATE DATABASE DBT_TEMPLATE_PROJECT_DATABASE COMMENT = 'dbt template';

-- creating an access role
CREATE ROLE DBT_TEMPLATE_PROJECT_TRANSFORMER COMMENT = 'Role for dbt';

-- granting role permissions
GRANT USAGE,OPERATE ON WAREHOUSE DBT_TEMPLATE_PROJECT_TRANSFORMING TO ROLE DBT_TEMPLATE_PROJECT_TRANSFORMER;
GRANT USAGE,CREATE SCHEMA ON DATABASE DBT_TEMPLATE_PROJECT_DATABASE TO ROLE DBT_TEMPLATE_PROJECT_TRANSFORMER;

GRANT USAGE ON DATABASE DBT_TEMPLATE_PROJECT_DATABASE TO ROLE DBT_TEMPLATE_PROJECT_TRANSFORMER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DBT_TEMPLATE_PROJECT_DATABASE TO ROLE DBT_TEMPLATE_PROJECT_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN DATABASE DBT_TEMPLATE_PROJECT_DATABASE TO ROLE DBT_TEMPLATE_PROJECT_TRANSFORMER;

GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DBT_TEMPLATE_PROJECT_DATABASE TO ROLE DBT_TEMPLATE_PROJECT_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN DATABASE DBT_TEMPLATE_PROJECT_DATABASE TO ROLE DBT_TEMPLATE_PROJECT_TRANSFORMER;


-- creating user and associating with role
CREATE USER DBT_TEMPLATE_PROJECT_DBT_CLOUD PASSWORD='CHANGE_ME' DEFAULT_ROLE = DBT_TEMPLATE_PROJECT_TRANSFORMER;
-- Make sure you change the above password! Add the flag -- MUST_CHANGE_PASSWORD = true to force a password change too
GRANT ROLE DBT_TEMPLATE_PROJECT_TRANSFORMER TO USER DBT_TEMPLATE_PROJECT_DBT_CLOUD;

-- grant all roles to sysadmin (always do this)
GRANT ROLE DBT_TEMPLATE_PROJECT_TRANSFORMER  TO ROLE SYSADMIN;

-- create schemas
CREATE SCHEMA DBT_TEMPLATE_PROJECT_DATABASE.WEBSITE;
CREATE SCHEMA DBT_TEMPLATE_PROJECT_DATABASE.workday;
CREATE SCHEMA DBT_TEMPLATE_PROJECT_DATABASE.analytics;