version: 2

sources:
  - name: public
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _airbyte_emitted_at
    tables:
      - name: fake_content
      - name: fake_data_employees
      - name: fake_sub_activate
      - name: fake_sub_deactivate
      - name: fake_web_events
        freshness: # make this a little more strict
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}