from setuptools import find_packages, setup

setup(
    name="modern_data_stack_assets",
    version="0+dev",
    author="Elementl",
    author_email="hello@elementl.com",
    classifiers=[
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Operating System :: OS Independent",
    ],
    packages=find_packages(exclude=["test"]),
    package_data={"modern_data_stack_assets": ["mds_dbt/*"]},
    install_requires=[
        "aiobotocore==1.3.3",
        "dagit",
        "dagster",
        "dagster-airbyte",
        "dagster-aws",
        "dagster-dbt",
        "dagster-ge",
        "dagster-pandas",
        "dagster-pyspark",
        "dagster-slack",
        "dagster-postgres",
        "dbt-core",
        "dbt-duckdb",
        "dbt-snowflake",
        "duckdb!=0.3.3",  # missing wheels
        "faker",
        "faker_music",
        "mock",
        # DataFrames were not written to Snowflake, causing errors
        "pandas<1.4.0",
        "pyarrow>=4.0.0",
        "pyspark",
        "requests",
        "gcsfs",
        "great-expectations",
        "fsspec",
        "s3fs",
        "scipy",
        "sklearn",
        "snowflake-sqlalchemy",
    ],
    extras_require={"tests": ["mypy", "pylint", "pytest"]},
)
